name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd trade_api || git clone https://github.com/YOUR_USERNAME/trade_api.git && cd trade_api
            git pull origin main
            docker stop $(docker ps -q) || true
            docker build -t trade_api .
            docker run -d -p 8000:8000 trade_api
